name: Publish Pages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: codeberg-small
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install Nix
        uses: https://github.com/cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31

      - name: Build site
        run: nix build .#site

      - name: Publish to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@2b24bbb7ff943d3c8fe1df91326adec66daea6dd # v2.2.0
        with:
          site: "https://${{ forge.repository_owner }}.codeberg.page/sc/"
          token: ${{ forge.token }}
          source: result/
