use sc_core::config::Config;
use sc_core::ipc::TuningResponse;

use crate::optimize::{OptimizedConfig, OptimizedFan};

/// Emit a complete NixOS module file from the config and optimization results.
pub fn emit_nix(
    config: &Config,
    optimized: &OptimizedConfig,
    tuning: Option<&TuningResponse>,
) -> String {
    let mut out = String::new();

    // Header comment
    out.push_str("# Generated by: sc-nixgen\n");
    if let Some(t) = tuning {
        let n_coupling = t.coupling_matrix.len();
        let avg_r2 = if n_coupling > 0 {
            t.coupling_matrix.iter().map(|c| c.r_squared).sum::<f64>() / n_coupling as f64
        } else {
            0.0
        };
        out.push_str(&format!(
            "# Coupling entries: {}, avg R² = {:.3}\n",
            n_coupling, avg_r2
        ));
        if !t.step_responses.is_empty() {
            let total_events: usize = t.step_responses.iter().map(|s| s.n_events).sum();
            out.push_str(&format!("# Step response events: {}\n", total_events));
        }
    }
    if !optimized.has_tuning_data {
        out.push_str("# WARNING: No tuning data available, using original curves unchanged\n");
        out.push_str("# Run the daemon and collect data, then re-run sc-nixgen\n");
    }

    // Detect unique hwmon chips for kernel modules
    let mut kernel_modules: Vec<String> = Vec::new();
    for sensor in &config.sensors {
        let module = hwmon_to_kernel_module(&sensor.hwmon);
        if !kernel_modules.contains(&module) {
            kernel_modules.push(module);
        }
    }
    for fan in &config.fans {
        let module = hwmon_to_kernel_module(&fan.hwmon);
        if !kernel_modules.contains(&module) {
            kernel_modules.push(module);
        }
    }

    out.push_str("{inputs, ...}: let\n");
    out.push_str("  inherit (inputs.sc.inputs.ronix.lib) mkRON;\n");
    out.push_str("in {\n");

    // Kernel modules
    if !kernel_modules.is_empty() {
        out.push_str("  boot.kernelModules = [");
        for m in &kernel_modules {
            out.push_str(&format!(" \"{}\"", m));
        }
        out.push_str(" ];\n\n");
    }

    // Build the settings struct and serialize with ronix
    let settings = build_settings(config, optimized);
    let mut settings_nix =
        ronix::to_nix(&settings).unwrap_or_else(|e| panic!("ronix serialization failed: {}", e));

    // Wrap topology enum values with mkRON "enum" for correct RON generation
    settings_nix = wrap_topology_enums(&settings_nix);

    out.push_str("  services.smartcool = {\n");
    out.push_str("    enable = true;\n");

    // Indent the ronix output to sit under services.smartcool.settings
    let indented = indent_block(&settings_nix, 4);
    out.push_str(&format!("    settings = {};\n", indented));

    out.push_str("  };\n");
    out.push_str("}\n");

    out
}

/// Emit Nix from a detected config with no tuning data (pass-through curves).
pub fn emit_nix_from_detected(config: &Config) -> String {
    use sc_core::config::CurvePoint;

    let optimized = OptimizedConfig {
        fans: config
            .fans
            .iter()
            .map(|f| OptimizedFan {
                name: f.name.clone(),
                sensors: f.sensors.clone(),
                curve: f
                    .curve
                    .iter()
                    .map(|p| CurvePoint {
                        temp: p.temp,
                        pwm: p.pwm,
                    })
                    .collect(),
                gamma: 1.0,
                max_beta: 0.0,
            })
            .collect(),
        has_tuning_data: false,
    };
    emit_nix(config, &optimized, None)
}

/// Build a serializable settings struct from optimized config.
fn build_settings(config: &Config, optimized: &OptimizedConfig) -> Settings {
    Settings {
        poll_interval_ms: config.poll_interval_ms,
        derivative: Derivative {
            window_size: config.derivative.window_size,
            boost_threshold: config.derivative.boost_threshold,
            decay_rate: config.derivative.decay_rate,
        },
        sensors: config
            .sensors
            .iter()
            .map(|s| Sensor {
                name: s.name.clone(),
                hwmon: s.hwmon.clone(),
                index: s.index,
                hwmon_instance: s.hwmon_instance,
            })
            .collect(),
        fans: optimized
            .fans
            .iter()
            .map(|opt_fan| {
                let orig = config.fans.iter().find(|f| f.name == opt_fan.name).unwrap();
                Fan {
                    name: opt_fan.name.clone(),
                    hwmon: orig.hwmon.clone(),
                    pwm_index: orig.pwm_index,
                    hwmon_instance: orig.hwmon_instance,
                    topology: orig.topology.clone(),
                    sensors: opt_fan.sensors.clone(),
                    curve: opt_fan
                        .curve
                        .iter()
                        .map(|p| CurvePointOut {
                            temp: p.temp,
                            pwm: p.pwm,
                        })
                        .collect(),
                }
            })
            .collect(),
        tuning: Tuning {
            ewma_span: config.tuning.ewma_span,
            ccf_buffer_size: config.tuning.ccf_buffer_size,
            ccf_max_lag: config.tuning.ccf_max_lag,
            step_threshold: config.tuning.step_threshold,
            response_window: config.tuning.response_window,
            regression_min_samples: config.tuning.regression_min_samples,
        },
    }
}

/// Indent every line of a multi-line string by `n` spaces, except the first line.
fn indent_block(s: &str, n: usize) -> String {
    let pad = " ".repeat(n);
    let mut lines = s.lines();
    let mut out = String::new();
    if let Some(first) = lines.next() {
        out.push_str(first);
    }
    for line in lines {
        out.push('\n');
        if !line.is_empty() {
            out.push_str(&pad);
        }
        out.push_str(line);
    }
    out
}

/// Wrap topology enum values in the Nix output with `mkRON "enum"` calls.
/// ronix::to_nix() emits enum variants as quoted strings (e.g. `position = "front";`)
/// but ronixLib.toRON needs them as `mkRON "enum" "front"` to produce unquoted RON identifiers.
fn wrap_topology_enums(nix: &str) -> String {
    let position_values: &[&str] = &[
        "front", "rear", "top", "bottom", "side", "cpu_cooler", "gpu_cooler",
    ];
    let direction_values: &[&str] = &["intake", "exhaust"];

    let mut result = nix.to_string();
    for val in position_values {
        let from = format!("position = \"{}\";", val);
        let to = format!("position = mkRON \"enum\" \"{}\";", val);
        result = result.replace(&from, &to);
    }
    for val in direction_values {
        let from = format!("direction = \"{}\";", val);
        let to = format!("direction = mkRON \"enum\" \"{}\";", val);
        result = result.replace(&from, &to);
    }
    result
}

/// Map hwmon chip name to kernel module name.
fn hwmon_to_kernel_module(hwmon: &str) -> String {
    if hwmon.starts_with("nct6") {
        "nct6775".to_string()
    } else {
        hwmon.to_string()
    }
}

// ─── Serializable Nix output types ──────────────────────────────────────────

#[derive(serde::Serialize)]
struct Settings {
    poll_interval_ms: u64,
    derivative: Derivative,
    sensors: Vec<Sensor>,
    fans: Vec<Fan>,
    tuning: Tuning,
}

#[derive(serde::Serialize)]
struct Derivative {
    window_size: usize,
    boost_threshold: f64,
    decay_rate: f64,
}

#[derive(serde::Serialize)]
struct Sensor {
    name: String,
    hwmon: String,
    index: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    hwmon_instance: Option<u32>,
}

#[derive(serde::Serialize)]
struct Fan {
    name: String,
    hwmon: String,
    pwm_index: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    hwmon_instance: Option<u32>,
    topology: sc_core::config::FanTopology,
    sensors: Vec<String>,
    curve: Vec<CurvePointOut>,
}

#[derive(serde::Serialize)]
struct CurvePointOut {
    temp: u32,
    pwm: u8,
}

#[derive(serde::Serialize)]
struct Tuning {
    ewma_span: usize,
    ccf_buffer_size: usize,
    ccf_max_lag: usize,
    step_threshold: u8,
    response_window: usize,
    regression_min_samples: usize,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::optimize::{OptimizedConfig, OptimizedFan};
    use sc_core::config::*;

    #[test]
    fn emit_produces_valid_nix_structure() {
        let config = Config {
            poll_interval_ms: 2000,
            derivative: DerivativeConfig {
                window_size: 10,
                boost_threshold: 2.0,
                decay_rate: 0.5,
            },
            sensors: vec![SensorConfig {
                name: "cpu".into(),
                hwmon: "k10temp".into(),
                index: 1,
                hwmon_instance: None,
            }],
            fans: vec![FanConfig {
                name: "fan".into(),
                hwmon: "nct6799".into(),
                pwm_index: 1,
                hwmon_instance: None,
                topology: FanTopology {
                    position: FanPosition::Front,
                    direction: AirflowDirection::Intake,
                    group: None,
                },
                sensors: vec!["cpu".into()],
                curve: vec![
                    CurvePoint { temp: 45, pwm: 20 },
                    CurvePoint { temp: 85, pwm: 200 },
                ],
            }],
            tuning: Default::default(),
        };

        let optimized = OptimizedConfig {
            fans: vec![OptimizedFan {
                name: "fan".into(),
                sensors: vec!["cpu".into()],
                curve: vec![
                    CurvePoint { temp: 45, pwm: 20 },
                    CurvePoint { temp: 85, pwm: 200 },
                ],
                gamma: 1.0,
                max_beta: 0.0,
            }],
            has_tuning_data: false,
        };

        let nix = emit_nix(&config, &optimized, None);

        assert!(nix.contains("services.smartcool"));
        assert!(nix.contains("enable = true"));
        assert!(nix.contains("poll_interval_ms = 2000;"));
        assert!(nix.contains("nct6775"));
        assert!(nix.contains("WARNING: No tuning data"));
        assert!(nix.contains("inherit (inputs.sc.inputs.ronix.lib) mkRON;"));
        assert!(nix.contains(r#"position = mkRON "enum" "front";"#));
        assert!(nix.contains(r#"direction = mkRON "enum" "intake";"#));
    }

    #[test]
    fn hwmon_nct_maps_to_nct6775() {
        assert_eq!(hwmon_to_kernel_module("nct6799"), "nct6775");
        assert_eq!(hwmon_to_kernel_module("nct6798"), "nct6775");
    }

    #[test]
    fn hwmon_other_passes_through() {
        assert_eq!(hwmon_to_kernel_module("k10temp"), "k10temp");
        assert_eq!(hwmon_to_kernel_module("it8622"), "it8622");
    }

    #[test]
    fn indent_block_works() {
        let input = "{\n  x = 1;\n}";
        let result = indent_block(input, 4);
        assert_eq!(result, "{\n      x = 1;\n    }");
    }
}
