use sc_core::config::Config;
use sc_core::ipc::TuningResponse;

use crate::optimize::OptimizedConfig;

/// Emit a complete NixOS module file from the config and optimization results.
pub fn emit_nix(
    config: &Config,
    optimized: &OptimizedConfig,
    tuning: Option<&TuningResponse>,
) -> String {
    let mut out = String::new();

    // Header comment
    out.push_str("# Generated by: sc-nixgen\n");
    if let Some(t) = tuning {
        let n_coupling = t.coupling_matrix.len();
        let avg_r2 = if n_coupling > 0 {
            t.coupling_matrix.iter().map(|c| c.r_squared).sum::<f64>() / n_coupling as f64
        } else {
            0.0
        };
        out.push_str(&format!(
            "# Coupling entries: {}, avg R² = {:.3}\n",
            n_coupling, avg_r2
        ));
        if !t.step_responses.is_empty() {
            let total_events: usize = t.step_responses.iter().map(|s| s.n_events).sum();
            out.push_str(&format!(
                "# Step response events: {}\n",
                total_events
            ));
        }
    }
    if !optimized.has_tuning_data {
        out.push_str("# WARNING: No tuning data available, using original curves unchanged\n");
        out.push_str("# Run the daemon and collect data, then re-run sc-nixgen\n");
    }

    // Detect unique hwmon chips for kernel modules
    let mut kernel_modules: Vec<String> = Vec::new();
    for sensor in &config.sensors {
        let module = hwmon_to_kernel_module(&sensor.hwmon);
        if !kernel_modules.contains(&module) {
            kernel_modules.push(module);
        }
    }
    for fan in &config.fans {
        let module = hwmon_to_kernel_module(&fan.hwmon);
        if !kernel_modules.contains(&module) {
            kernel_modules.push(module);
        }
    }

    out.push_str("_: {\n");

    // Kernel modules
    if !kernel_modules.is_empty() {
        out.push_str("  boot.kernelModules = [");
        for m in &kernel_modules {
            out.push_str(&format!(" \"{}\"", m));
        }
        out.push_str(" ];\n\n");
    }

    out.push_str("  services.smartcool = {\n");
    out.push_str("    enable = true;\n");
    out.push_str("    settings = {\n");

    // poll_interval_ms
    out.push_str(&format!("      poll_interval_ms = {};\n\n", config.poll_interval_ms));

    // derivative
    out.push_str("      derivative = {\n");
    out.push_str(&format!("        window_size = {};\n", config.derivative.window_size));
    out.push_str(&format!("        boost_threshold = {};\n", format_float(config.derivative.boost_threshold)));
    out.push_str(&format!("        decay_rate = {};\n", format_float(config.derivative.decay_rate)));
    out.push_str("      };\n\n");

    // sensors
    out.push_str("      sensors = [\n");
    for s in &config.sensors {
        out.push_str(&format!(
            "        {{ name = \"{}\"; hwmon = \"{}\"; index = {}; }}\n",
            s.name, s.hwmon, s.index
        ));
    }
    out.push_str("      ];\n\n");

    // fans (optimized)
    out.push_str("      fans = [\n");
    for opt_fan in &optimized.fans {
        let orig = config.fans.iter().find(|f| f.name == opt_fan.name).unwrap();
        out.push_str("        {\n");
        out.push_str(&format!("          name = \"{}\";\n", opt_fan.name));
        out.push_str(&format!("          hwmon = \"{}\";\n", orig.hwmon));
        out.push_str(&format!("          pwm_index = {};\n", orig.pwm_index));

        // Sensor assignment comment
        if optimized.has_tuning_data && opt_fan.max_beta > 0.0 {
            out.push_str(&format!(
                "          # max |beta| = {:.2}, gamma = {:.2}\n",
                opt_fan.max_beta, opt_fan.gamma
            ));
        }

        out.push_str("          sensors = [");
        for s in &opt_fan.sensors {
            out.push_str(&format!(" \"{}\"", s));
        }
        out.push_str(" ];\n");

        out.push_str("          curve = [\n");
        for point in &opt_fan.curve {
            out.push_str(&format!(
                "            {{ temp = {}; pwm = {}; }}\n",
                point.temp, point.pwm
            ));
        }
        out.push_str("          ];\n");
        out.push_str("        }\n");
    }
    out.push_str("      ];\n\n");

    // tuning
    out.push_str("      tuning = {\n");
    out.push_str(&format!("        ewma_span = {};\n", config.tuning.ewma_span));
    out.push_str(&format!("        ccf_buffer_size = {};\n", config.tuning.ccf_buffer_size));
    out.push_str(&format!("        ccf_max_lag = {};\n", config.tuning.ccf_max_lag));
    out.push_str(&format!("        step_threshold = {};\n", config.tuning.step_threshold));
    out.push_str(&format!("        response_window = {};\n", config.tuning.response_window));
    out.push_str(&format!("        regression_min_samples = {};\n", config.tuning.regression_min_samples));
    out.push_str("      };\n");

    out.push_str("    };\n");
    out.push_str("  };\n");
    out.push_str("}\n");

    out
}

/// Map hwmon chip name to kernel module name.
fn hwmon_to_kernel_module(hwmon: &str) -> String {
    // nct6799 is loaded via the nct6775 driver
    if hwmon.starts_with("nct6") {
        "nct6775".to_string()
    } else {
        // k10temp, it87xx, etc. are typically auto-loaded or match the chip name
        hwmon.to_string()
    }
}

/// Format a float without trailing zeros, ensuring at least one decimal place.
fn format_float(v: f64) -> String {
    let s = format!("{}", v);
    if s.contains('.') {
        s
    } else {
        format!("{}.0", s)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sc_core::config::*;
    use crate::optimize::{OptimizedConfig, OptimizedFan};

    #[test]
    fn emit_produces_valid_nix_structure() {
        let config = Config {
            poll_interval_ms: 2000,
            derivative: DerivativeConfig {
                window_size: 10,
                boost_threshold: 2.0,
                decay_rate: 0.5,
            },
            sensors: vec![SensorConfig {
                name: "cpu".into(),
                hwmon: "k10temp".into(),
                index: 1,
            }],
            fans: vec![FanConfig {
                name: "fan".into(),
                hwmon: "nct6799".into(),
                pwm_index: 1,
                sensors: vec!["cpu".into()],
                curve: vec![
                    CurvePoint { temp: 45, pwm: 20 },
                    CurvePoint { temp: 85, pwm: 200 },
                ],
            }],
            tuning: Default::default(),
        };

        let optimized = OptimizedConfig {
            fans: vec![OptimizedFan {
                name: "fan".into(),
                sensors: vec!["cpu".into()],
                curve: vec![
                    CurvePoint { temp: 45, pwm: 20 },
                    CurvePoint { temp: 85, pwm: 200 },
                ],
                gamma: 1.0,
                max_beta: 0.0,
            }],
            has_tuning_data: false,
        };

        let nix = emit_nix(&config, &optimized, None);

        assert!(nix.contains("services.smartcool"));
        assert!(nix.contains("enable = true"));
        assert!(nix.contains("poll_interval_ms = 2000"));
        assert!(nix.contains("nct6775"));
        assert!(nix.contains("name = \"cpu\""));
        assert!(nix.contains("name = \"fan\""));
        assert!(nix.contains("WARNING: No tuning data"));
    }

    #[test]
    fn hwmon_nct_maps_to_nct6775() {
        assert_eq!(hwmon_to_kernel_module("nct6799"), "nct6775");
        assert_eq!(hwmon_to_kernel_module("nct6798"), "nct6775");
    }

    #[test]
    fn hwmon_other_passes_through() {
        assert_eq!(hwmon_to_kernel_module("k10temp"), "k10temp");
        assert_eq!(hwmon_to_kernel_module("it8622"), "it8622");
    }
}
